//render links

###single contacts request
GET https://cse341-project1-contacts.onrender.com/contacts/66ed2c44e7da3bd294b1f346


###all contacts request
GET https://cse341-project1-contacts.onrender.com/contacts


###Create contact
POST https://cse341-project1-contacts.onrender.com/contacts
content-type: application/json

{
    "firstName": "Ashley",
    "lastName": "Weaver",
    "email": "aWeaver@test.com",
    "favoriteColor": "Brown",
    "birthday": "1994-12-05"
}

###update contact
PUT https://cse341-project1-contacts.onrender.com/contacts/66f2117222565e7d3f4b3a31
content-type: application/json

{
    "firstName": "Ashley",
    "lastName": "Weaver but updated",
    "email": "aWeaver@test.com",
    "favoriteColor": "Brown",
    "birthday": "1994-12-05"
}

###single contacts request
DELETE https://cse341-project1-contacts.onrender.com/contacts/66f2117222565e7d3f4b3a31





//Localhost links

###single contacts request
GET http://localhost:3000/contacts/66f20e02f5eba225a12be4ea


###all contacts request
GET http://localhost:3000/contacts


###Create contact
POST http://localhost:3000/contacts
content-type: application/json

{
    "firstName": "Ashley",
    "lastName": "Weaver",
    "email": "aWeaver@test.com",
    "favoriteColor": "Brown",
    "birthday": "1994-12-05"
}

###update contact
PUT http://localhost:3000/contacts/66f20e02f5eba225a12be4ea
content-type: application/json

{
    "firstName": "Ashley",
    "lastName": "Weaver but updated",
    "email": "aWeaver@test.com",
    "favoriteColor": "Brown",
    "birthday": "1994-12-05"
}

###single contacts request
DELETE http://localhost:3000/contacts/66f20a27306b952eada88a8d